import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { attributeConfigs, generateDts, generateEnvExample, generateJsonSchema } from "@puristic/env/index.js";
import { type AppConfig, loadWorkspace } from "./workspace.js";

export interface GenOptions {
    config?: string;
    out?: string;
    types: boolean;
    example: boolean;
    json: boolean;
    force: boolean;
    cwd?: string;
}

export async function gen(options: GenOptions): Promise<{ written: string[] }> {
    const cwd = options.cwd ?? process.cwd();
    const workspace = await loadWorkspace(cwd, options.config);
    const configs = workspace.configsFor(join(cwd, ".env"));
    if (configs.length === 0) {
        throw new Error(`No env config found at or below ${cwd}. Pass --config <path>.`);
    }

    const outDir = options.out !== undefined ? resolve(cwd, options.out) : cwd;
    const descriptors = attributeConfigs(
        configs.map((config) => ({ configId: config.configId, app: config.app, descriptors: config.descriptors })),
    ).descriptors;
    const source = configs.map((config) => basename(config.path)).join(", ");

    const artifacts: { name: string; content: string }[] = [];
    if (options.types) {
        artifacts.push({ name: "purenv.d.ts", content: generateDts(descriptors, { source }) });
    }
    if (options.example) {
        artifacts.push({ name: ".env.example", content: generateEnvExample(descriptors, { source }) });
    }
    if (options.json) {
        artifacts.push(...jsonArtifacts(configs));
    }

    mkdirSync(outDir, { recursive: true });
    const written: string[] = [];
    for (const artifact of artifacts) {
        const target = join(outDir, artifact.name);
        guardOverwrite(target, artifact.content, options.force);
        writeFileSync(target, artifact.content);
        written.push(target);
    }
    return { written };
}

// JSON Schema is per-schema (one zod object). A single config keeps purenv.schema.json; multiple app
// configs get one file each, since their nested shapes can't be merged into one document.
function jsonArtifacts(configs: AppConfig[]): { name: string; content: string }[] {
    if (configs.length === 1) {
        return [{ name: "purenv.schema.json", content: generateJsonSchema(configs[0]!.schema) }];
    }
    return configs.map((config) => ({
        name: `purenv.${config.app.replace(/[^\w.-]+/g, "-")}.schema.json`,
        content: generateJsonSchema(config.schema),
    }));
}

// Don't clobber a hand-written file that happens to share a generated artifact's name. Files that
// carry a comment banner (.d.ts, .env.example) are checked; JSON (which can't carry one) overwrites.
function guardOverwrite(target: string, content: string, force: boolean): void {
    if (force || !existsSync(target)) {
        return;
    }
    if (!content.startsWith("//") && !content.startsWith("#")) {
        return;
    }
    const firstLine = readFileSync(target, "utf8").split("\n", 1)[0] ?? "";
    if (!firstLine.includes("Generated by purenv gen")) {
        throw new Error(`Refusing to overwrite ${target} (not a purenv-generated artifact). Pass --force to overwrite.`);
    }
}
