import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { gen } from "./gen.js";

const fixtureConfig = fileURLToPath(new URL("../../vscode/fixtures/api/env.config.ts", import.meta.url));

let out: string;
beforeEach(() => {
    out = mkdtempSync(join(tmpdir(), "puristic-gen-"));
});
afterEach(() => {
    rmSync(out, { recursive: true, force: true });
});

describe("gen", () => {
    it("writes types, example, and schema; secrets stay blank; runs are idempotent", async () => {
        const result = await gen({ config: fixtureConfig, out, types: true, example: true, json: true, force: false });
        expect(result.written.map((path) => path.replace(`${out}/`, ""))).toEqual([
            "puristic-env.d.ts",
            ".env.example",
            "puristic.schema.json",
        ]);

        const dts = readFileSync(join(out, "puristic-env.d.ts"), "utf8");
        expect(dts).toContain("interface ProcessEnv {");
        expect(dts).toContain("SERVER_PORT: string;");
        expect(dts).toContain("export interface PuristicConfig {");

        const example = readFileSync(join(out, ".env.example"), "utf8");
        expect(example).toContain("SERVER_HOST=0.0.0.0");
        expect(example).toMatch(/^DATABASE_URL=$/m);

        expect(JSON.parse(readFileSync(join(out, "puristic.schema.json"), "utf8")).type).toBe("object");

        const before = readFileSync(join(out, ".env.example"), "utf8");
        await gen({ config: fixtureConfig, out, types: true, example: true, json: true, force: false });
        expect(readFileSync(join(out, ".env.example"), "utf8")).toBe(before);
    });

    it("refuses to overwrite a hand-written file without --force", async () => {
        writeFileSync(join(out, ".env.example"), "HAND_WRITTEN=1\n");
        await expect(gen({ config: fixtureConfig, out, types: false, example: true, json: false, force: false })).rejects.toThrow(
            /Refusing to overwrite/,
        );

        await gen({ config: fixtureConfig, out, types: false, example: true, json: false, force: true });
        expect(readFileSync(join(out, ".env.example"), "utf8")).toContain("Generated by puristic gen");
    });
});
