import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { generateDts, generateEnvExample, generateJsonSchema, inspectSchema, loadDefinition } from "@puristic/env/index.js";
import { findNearestConfig } from "./discoverConfig.js";

export interface GenOptions {
    config?: string;
    out?: string;
    types: boolean;
    example: boolean;
    json: boolean;
    force: boolean;
    cwd?: string;
}

export async function gen(options: GenOptions): Promise<{ written: string[] }> {
    const cwd = options.cwd ?? process.cwd();
    const configPath = resolveConfigPath(options.config, cwd);
    const outDir = options.out !== undefined ? resolve(cwd, options.out) : dirname(configPath);
    const definition = await loadDefinition(configPath);
    const descriptors = inspectSchema(definition.schema);
    const source = basename(configPath);

    const artifacts: { name: string; content: string }[] = [];
    if (options.types) {
        artifacts.push({ name: "puristic-env.d.ts", content: generateDts(descriptors, { source }) });
    }
    if (options.example) {
        artifacts.push({ name: ".env.example", content: generateEnvExample(descriptors, { source }) });
    }
    if (options.json) {
        artifacts.push({ name: "puristic.schema.json", content: generateJsonSchema(definition.schema) });
    }

    mkdirSync(outDir, { recursive: true });
    const written: string[] = [];
    for (const artifact of artifacts) {
        const target = join(outDir, artifact.name);
        guardOverwrite(target, artifact.content, options.force);
        writeFileSync(target, artifact.content);
        written.push(target);
    }
    return { written };
}

function resolveConfigPath(config: string | undefined, cwd: string): string {
    if (config !== undefined) {
        return resolve(cwd, config);
    }
    const found = findNearestConfig(cwd);
    if (found === undefined) {
        throw new Error(`No env.config.* found at or above ${cwd}. Pass --config <path>.`);
    }
    return found;
}

// Don't clobber a hand-written file that happens to share a generated artifact's name. Files that
// carry a comment banner (.d.ts, .env.example) are checked; JSON (which can't carry one) overwrites.
function guardOverwrite(target: string, content: string, force: boolean): void {
    if (force || !existsSync(target)) {
        return;
    }
    if (!content.startsWith("//") && !content.startsWith("#")) {
        return;
    }
    const firstLine = readFileSync(target, "utf8").split("\n", 1)[0] ?? "";
    if (!firstLine.includes("Generated by puristic gen")) {
        throw new Error(`Refusing to overwrite ${target} (not a puristic-generated artifact). Pass --force to overwrite.`);
    }
}
