import type { LeafDescriptorPublic } from "../inspectSchema.js";
import { formatLeafComment } from "./formatLeafComment.js";

const BANNER = "# Generated by puristic gen — DO NOT EDIT.";

export interface CodegenOptions {
    source?: string;
}

// Render a .env.example grouped by top-level schema section. Each key is preceded by a comment
// describing its type/requiredness/default; secret values are always left blank.
export function generateEnvExample(descriptors: LeafDescriptorPublic[], options: CodegenOptions = {}): string {
    const header = options.source === undefined ? [BANNER] : [BANNER, `# Source: ${options.source}`];

    const rootLeaves: LeafDescriptorPublic[] = [];
    const sections = new Map<string, LeafDescriptorPublic[]>();
    for (const descriptor of descriptors) {
        if (descriptor.path.length <= 1) {
            rootLeaves.push(descriptor);
            continue;
        }
        const section = descriptor.path[0] ?? "";
        const existing = sections.get(section);
        if (existing === undefined) {
            sections.set(section, [descriptor]);
        } else {
            existing.push(descriptor);
        }
    }

    const blocks: string[] = [];
    if (rootLeaves.length > 0) {
        blocks.push(rootLeaves.map(entry).join("\n"));
    }
    for (const [section, leaves] of sections) {
        blocks.push(`# --- ${section} ---\n${leaves.map(entry).join("\n")}`);
    }

    return `${header.join("\n")}\n\n${blocks.join("\n\n")}\n`;
}

function entry(descriptor: LeafDescriptorPublic): string {
    const lines = [`# ${formatLeafComment(descriptor)}`];
    if (descriptor.secret) {
        lines.push("# secret: set via `puristic encrypt`, or paste an encrypted:v1: envelope");
        lines.push(`${descriptor.envName}=`);
        return lines.join("\n");
    }
    if (descriptor.hasDefault && descriptor.default !== undefined) {
        lines.push(`${descriptor.envName}=${literal(descriptor.default)}`);
        return lines.join("\n");
    }
    lines.push(`${descriptor.envName}=`);
    return lines.join("\n");
}

function literal(value: unknown): string {
    return typeof value === "string" ? value : String(value);
}
