import { describe, expect, it } from "vitest";
import { z } from "zod";
import { inspectSchema } from "../inspectSchema.js";
import { generateEnvExample } from "./generateEnvExample.js";

const descriptors = inspectSchema(
    z.object({
        nodeEnv: z.string(),
        server: z.object({
            port: z.coerce.number().int(),
            host: z.string().default("0.0.0.0"),
        }),
        database: z.object({
            url: z.url().meta({ secret: true }),
        }),
    }),
);

describe("generateEnvExample", () => {
    const out = generateEnvExample(descriptors, { source: "env.config.ts" });

    it("includes the banner and source", () => {
        expect(out.startsWith("# Generated by puristic gen — DO NOT EDIT.\n# Source: env.config.ts")).toBe(true);
    });

    it("renders root keys, section headers, and defaults", () => {
        expect(out).toContain("NODE_ENV=");
        expect(out).toContain("# --- server ---");
        expect(out).toContain("SERVER_PORT=");
        expect(out).toContain("SERVER_HOST=0.0.0.0");
        expect(out).toContain("# --- database ---");
    });

    it("leaves secrets blank with a hint and never emits their value", () => {
        expect(out).toContain("# secret: set via `puristic encrypt`");
        expect(out).toMatch(/DATABASE_URL=\n?$/);
        expect(out).not.toContain("DATABASE_URL=encrypted");
    });
});
