import type { LeafDescriptorPublic, LeafTypeTag } from "../inspectSchema.js";
import { formatLeafComment } from "./formatLeafComment.js";
import type { CodegenOptions } from "./generateEnvExample.js";

const BANNER = "// Generated by puristic gen — DO NOT EDIT.";

// Coerced (runtime) TS type per leaf type tag — the shape createConfig().load() returns.
const SCALAR: Record<LeafTypeTag, string> = {
    string: "string",
    number: "number",
    boolean: "boolean",
    bigint: "bigint",
    date: "Date",
    enum: "string",
    literal: "string",
    unknown: "unknown",
};

type Branch = Map<string, Branch | LeafDescriptorPublic>;

// Emit a global NodeJS.ProcessEnv augmentation (raw string values, keyed by env var name) plus a
// typed PuristicConfig interface mirroring the nested, coerced schema shape.
export function generateDts(descriptors: LeafDescriptorPublic[], options: CodegenOptions = {}): string {
    const lines = [BANNER];
    if (options.source !== undefined) {
        lines.push(`// Source: ${options.source}`);
    }
    lines.push("", "export {};", "", "declare global {", "    namespace NodeJS {", "        interface ProcessEnv {");
    for (const descriptor of descriptors) {
        lines.push(`            /** ${formatLeafComment(descriptor)} */`);
        lines.push(`            ${descriptor.envName}${rawOptional(descriptor) ? "?" : ""}: ${rawType(descriptor)};`);
    }
    lines.push("        }", "    }", "}", "");
    lines.push("/** Parsed + coerced config — the shape returned by createConfig(definition).load(). */");
    lines.push(`export interface PuristicConfig ${renderBranch(buildTree(descriptors), 0)}`);
    return `${lines.join("\n")}\n`;
}

function rawOptional(descriptor: LeafDescriptorPublic): boolean {
    return descriptor.optional || descriptor.hasDefault;
}

function rawType(descriptor: LeafDescriptorPublic): string {
    return descriptor.enumValues !== undefined ? union(descriptor.enumValues) : "string";
}

function buildTree(descriptors: LeafDescriptorPublic[]): Branch {
    const root: Branch = new Map();
    for (const descriptor of descriptors) {
        let branch = root;
        for (let i = 0; i < descriptor.path.length - 1; i++) {
            const key = descriptor.path[i] ?? "";
            const child = branch.get(key);
            if (child instanceof Map) {
                branch = child;
            } else {
                const created: Branch = new Map();
                branch.set(key, created);
                branch = created;
            }
        }
        branch.set(descriptor.path[descriptor.path.length - 1] ?? descriptor.envName, descriptor);
    }
    return root;
}

function renderBranch(branch: Branch, depth: number): string {
    const pad = "    ".repeat(depth + 1);
    const lines = ["{"];
    for (const [key, value] of branch) {
        if (value instanceof Map) {
            lines.push(`${pad}${key}: ${renderBranch(value, depth + 1)};`);
        } else {
            lines.push(`${pad}${key}${configOptional(value) ? "?" : ""}: ${configType(value)};`);
        }
    }
    lines.push(`${"    ".repeat(depth)}}`);
    return lines.join("\n");
}

function configOptional(descriptor: LeafDescriptorPublic): boolean {
    return descriptor.optional || descriptor.hasDefault;
}

function configType(descriptor: LeafDescriptorPublic): string {
    const base = descriptor.enumValues !== undefined ? union(descriptor.enumValues) : SCALAR[descriptor.type];
    return descriptor.nullable ? `${base} | null` : base;
}

function union(values: string[]): string {
    return values.map((value) => JSON.stringify(value)).join(" | ");
}
